### PR TITLE
@PlatformIO Library Registry manifest file

### PR DESCRIPTION
**Pull request by ivankravets**
- This library in Web Registry: http://platformio.org/#!/lib/show/427/CC3000_MDNS
- Specification: [PlatformIO Library Manager](http://docs.platformio.org/en/latest/librarymanager/index.html)
- Integration: [IDE Integration](http://docs.platformio.org/en/latest/ide.html)

### CODE REVIEW

**Comment by ladyada** [comment]
hiya we strongly recommend using the existing library.properties file

**Comment by ivankravets** [comment]
Dear @ladyada ,

1. Where is manifest specification of "library.properties"?
2. PlatformIO proposes unified library manifest named [library.json](http://docs.platformio.org/en/latest/librarymanager/config.html). It doesn't depend on specific framework or platforms. [library.json](http://docs.platformio.org/en/latest/librarymanager/config.html) allows developer to describe a structure, dependencies, examples, etc of the lib.

What is more, PlatformIO has crawler which analyses these [library.json](http://docs.platformio.org/en/latest/librarymanager/config.html) files and builds own Library Registry. This registry is used via PlatformIO Registry API by 3-rd party library managers, services and etc. For example:
- http://platformio.org/#!/lib
- https://libraries.io/platformio

Finally, please look into Continuous Integration with PlatformIO:
- https://github.com/ivankravets/aREST/blob/master/.travis.yml
- https://travis-ci.org/ivankravets/aREST

- https://github.com/felis/USB_Host_Shield_2.0/blob/master/.travis.yml
- https://travis-ci.org/felis/USB_Host_Shield_2.0

**Comment by ladyada** [comment]
here is the specification
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification
all of our libraries have a file in that format so either you can use that spec (which is now the standard for all Arduino libraries) or convince Arduino to use your specification, we have
 to meet theirs to be included in the library manager :)
thx!

**Comment by ivankravets** [comment]
> here is the specification

This isn't cross-platforms and cross-frameworks solution. I've see it earlier. Developer can't define dependencies, keep source code/examples in own structures and etc. I'm for universal and standardised solution.

> convince Arduino to use your specification

PlatformIO has support for 10+ development platforms and more then 150+ embedded boards. They are related to different platforms and have support for multiple frameworks. I'm think about users and developers, but not about companies which don't like PlatformIO or like to live in own "box" (I don't mean here Adafruit, thanks a lot for your job and efforts).

See our discussion here: https://groups.google.com/a/arduino.cc/forum/#!topic/developers/xCDjekcQW4k

P.S: It's OK! I'll not create pull requests in future with it. 

Have a nice day! :blush:

**Comment by vicatcu** [comment]
@ladyada As someone who has absolutely no stake in the outcome, what's the downside to adding a file to the repository?

**Comment by ladyada** [comment]
i have to maintain and manage hundreds of github repositories. more files == more maintenance.

**Pull request closed without merging**
